#!/bin/bash

rename() {
	local old_path=$1 char=$2
	echo "$old_path" | sed 's/^\([^.]*\)/\1'$char'/'
}

catalog_name=$1
archive_name=$2

cd $HOME
if [ ! -d $catalog_name ]
then
	mkdir $catalog_name
fi

count=0

for extension in $@
do 
	count=$(( $count + 1 ))
	if [ $count -ge 3 ] 
	then 
		paths=`find ~/techprog -name "*.$extension"` 
		for path in $paths
		do 
			src_filename=`basename "$path"` 
			old_path=$path 
			while [ -e $catalog_name/$src_filename ] 
			do 
				new_path=`rename "$path" "_"` 
				path=$new_path  
				src_filename=`basename "$path"` 
			done 
			cp "$old_path" "$catalog_name/$src_filename" 
		done 
	fi

done
tar -czf $archive_name "$catalog_name"
echo "done"
